import { UserInventory } from './Clicker';
import { ClickerAction } from './ClickerAction';
import { ClickerBuilding } from './ClickerBuilding';
import { ClickerResources } from './ClickerResource';
import { ClickerUnit } from './ClickerUnits';
import { ClickerUpgrade } from './ClickerUpgrade';

export const FieldTypes: string[] = ['Resources', 'Actions', 'Buildings', 'Units', 'Upgrades'];

export const ResourcesList: ClickerResources[] = [
    {
        Name: 'Food',
        Owned: 0,
        SpecialUnlock: false,
        Unlocked: true,
        UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Visible: true,
        VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
    },
    {
        Name: 'Lumber',
        Owned: 0,
        SpecialUnlock: false, 
        Unlocked: true,
        UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Visible: true,
        VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
    },
    {
        Name: 'Gold',
        Owned: 0,
        SpecialUnlock: false, 
        Unlocked: true,
        UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Visible: true,
        VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
    },
];

export const ActionList: ClickerAction[] = [
    {
        Name: 'Harvest Crops',
        ImagePath: 'assets/corn.png',
        Time: 1000,
        TimeLabel: '1s',
        ActionType: 'Harvest',
        ButtonType: 'Action',
        Description: '',
        ResourceAdded: [{Name: 'Food', Amount: 1}],
        Cost: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Disabled: false,
        Progress: 0,
        Owned: 1,
        SpecialUnlock: false, 
        Unlocked: true,
        UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Visible: true,
        VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
        FlavorText: 'Insert corny joke here.',
    },
    {
        Name: 'Chop Wood',
        ImagePath: 'assets/tree.png',
        Time: 1000,
        TimeLabel: '1s',
        ActionType: 'Harvest',
        ButtonType: 'Action',
        Description: '',
        ResourceAdded: [{Name: 'Lumber', Amount: 1}],
        Cost: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Disabled: false,
        Progress: 0,
        Owned: 1,
        SpecialUnlock: false, 
        Unlocked: true,
        UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Visible: true,
        VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
        FlavorText: 'Just like George Washington.',
    },
    {
        Name: 'Mine Gold',
        ImagePath: 'assets/gold-ore.png',
        Time: 5000,
        TimeLabel: '5s',
        ActionType: 'Harvest',
        ButtonType: 'Action',
        Description: '',
        ResourceAdded: [{Name: 'Gold', Amount: 1}],
        Cost: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Disabled: false,
        Progress: 0,
        Owned: 1,
        SpecialUnlock: false, 
        Unlocked: false,
        UnlockRequirements: {Resources: [{Name: 'Food', Amount: 10, Type: 'Resources'}, {Name: 'Lumber', Amount: 10, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Visible: true,
        VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
        FlavorText: '',
    },
];

export const BuildingsList: ClickerBuilding[] = [
    {
        Name: 'Mill',
        ImagePath: 'assets/windmill.png',
        Time: 10000,
        TimeLabel: '10s',
        ButtonType: 'Building',
        Description: '',
        ResourceAdded: [{Name: 'Food', Amount: 1}],
        Cost: {Resources: [{Name: 'Food', Amount: 15, Type: 'Resources'}, {Name: 'Lumber', Amount: 15, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Owned: 0,
        Progress: 0,
        SpecialUnlock: false,
        Unlocked: false,
        UnlockRequirements: {Resources: [{Name: 'Food', Amount: 15, Type: 'Resources'}, {Name: 'Lumber', Amount: 15, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Visible: true,
        VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
        FlavorText: 'Stop milling around!',
    },
    {
        Name: 'Lumber Yard',
        ImagePath: 'assets/logs.png',
        Time: 10000,
        TimeLabel: '10s',
        ButtonType: 'Building',
        Description: '',
        ResourceAdded: [{Name: 'Lumber', Amount: 1}],
        Cost: {Resources: [{Name: 'Lumber', Amount: 30, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Owned: 0,
        Progress: 0,
        SpecialUnlock: false, 
        Unlocked: false,
        UnlockRequirements: {Resources: [{Name: 'Lumber', Amount: 30, Type: 'Resources'}, {Name: 'Gold', Amount: 15, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Visible: true,
        VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
        FlavorText: '',
    },
    {
        Name: 'Gold Mine',
        ImagePath: 'assets/gold-mine.jpg',
        Time: 20000,
        TimeLabel: '20s',
        ButtonType: 'Building',
        Description: '',
        ResourceAdded: [{Name: 'Gold', Amount: 1}], Progress: 0,
        Cost: {Resources: [{Name: 'Lumber', Amount: 25, Type: 'Resources'}, {Name: 'Gold', Amount: 50, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Owned: 0,
        SpecialUnlock: false, 
        Unlocked: false,
        UnlockRequirements: {Resources: [], Actions: [], Buildings: [{Name: 'Mill', Amount: 1, Type: 'Buildings'}, {Name: 'Lumber Yard', Amount: 1, Type: 'Buildings'}], Units: [], Upgrades: []},
        Visible: false,
        VisibilityRequirements: {Resources: [{Name: 'Gold', Amount: 15, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
        FlavorText: '',
    },
];

export const UnitList: ClickerUnit[] = [
    {
        Name: 'Peasant',
        ImagePath: 'assets/peasant.png',
        ModifiedBuilding: 'Mill',
        ResourceAdded: [{Name: 'Food', Amount: 1}],
        ButtonType: 'Unit',
        Description: '',
        Cost: {Resources: [{Name: 'Food', Amount: 30, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Owned: 0,
        SpecialUnlock: false, 
        Unlocked: false,
        UnlockRequirements: {Resources: [], Actions: [], Buildings: [{Name: 'Mill', Amount: 1, Type: 'Buildings'}], Units: [], Upgrades: []},
        Visible: false,
        VisibilityRequirements: {Resources: [{Name: 'Food', Amount: 15, Type: 'Resources'}, {Name: 'Lumber', Amount: 15, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
        FlavorText: 'Yes, milord?',
    },
    {
        Name: 'Lumberjack',
        ImagePath: 'assets/lumberjack.png',
        ModifiedBuilding: 'Lumber Yard',
        ResourceAdded: [{Name: 'Lumber', Amount: 1}],
        ButtonType: 'Unit',
        Description: '',
        Cost: {Resources: [{Name: 'Food', Amount: 20, Type: 'Resources'}, {Name: 'Gold', Amount: 20, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Owned: 0,
        SpecialUnlock: false, 
        Unlocked: false,
        UnlockRequirements: {Resources: [], Actions: [], Buildings: [{Name: 'Lumber Yard', Amount: 1, Type: 'Buildings'}], Units: [], Upgrades: []},
        Visible: false,
        VisibilityRequirements: {Resources: [{Name: 'Lumber', Amount: 30, Type: 'Resources'}, {Name: 'Gold', Amount: 15, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
        FlavorText: 'Timber!',
    },
    {
        Name: 'Miner',
        ImagePath: 'assets/miner.jpg',
        ModifiedBuilding: 'Gold Mine',
        ResourceAdded: [{Name: 'Gold', Amount: 1}],
        ButtonType: 'Unit',
        Description: '',
        Cost:  {Resources: [{Name: 'Food', Amount: 30, Type: 'Resources'}, {Name: 'Gold', Amount: 30, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Owned: 0,
        SpecialUnlock: false, 
        Unlocked: false,
        UnlockRequirements: {Resources: [], Actions: [], Buildings: [{Name: 'Gold Mine', Amount: 1, Type: 'Buildings'}], Units: [], Upgrades: []},
        Visible: false,
        VisibilityRequirements: {Resources: [], Actions: [], Buildings: [{Name: 'Mill', Amount: 1, Type: 'Buildings'}, {Name: 'Lumber Yard', Amount: 1, Type: 'Buildings'}], Units: [], Upgrades: []},
        FlavorText: 'We\'ve got dwarves in the rutabagas!',
    },
];

export const UpgradesList: ClickerUpgrade[] = [
    {
        Name: 'Improved Hoes',
        ImagePath: 'assets/hoe.png',
        Description: 'Harvest twice as many crops.',
        Modify: 'Harvest Crops',
        ModifyType: 'Actions',
        ResourceAdded: [{Name: 'Food', Amount: 1}],
        ButtonType: 'Upgrade',
        Cost:  {Resources: [{Name: 'Lumber', Amount: 30, Type: 'Resources'}, {Name: 'Gold', Amount: 10, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Owned: 0,
        SpecialUnlock: false, 
        Unlocked: false,
        UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [{Name: 'Peasant', Amount: 1, Type: 'Units'}], Upgrades: []},
        Visible: false,
        VisibilityRequirements: {Resources: [], Actions: [], Buildings: [{Name: 'Mill', Amount: 1, Type: 'Buildings'}], Units: [], Upgrades: []},
        FlavorText: '',
        ModalData: {
            Title: '',
            Description: '',
            ButtonTitle: '',
            ModalUpgrades: [],
        }
    },
    {
        Name: 'Improved Axes',
        ImagePath: 'assets/axe.png',
        Description: 'Chop twice as much wood.',
        Modify: 'Chop Wood',
        ModifyType: 'Actions',
        ResourceAdded: [{Name: 'Lumber', Amount: 1}],
        ButtonType: 'Upgrade',
        Cost: {Resources: [{Name: 'Lumber', Amount: 50, Type: 'Resources'}, {Name: 'Gold', Amount: 30, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Owned: 0,
        SpecialUnlock: false, 
        Unlocked: false,
        UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [{Name: 'Lumberjack', Amount: 1, Type: 'Units'}], Upgrades: []},
        Visible: false,
        VisibilityRequirements: {Resources: [], Actions: [], Buildings: [{Name: 'Lumber Yard', Amount: 1, Type: 'Buildings'}], Units: [], Upgrades: []},
        FlavorText: '',
        ModalData: {
            Title: '',
            Description: '',
            ButtonTitle: '',
            ModalUpgrades: [],
        },
    },
    {
        Name: 'Improved Pickaxes',
        ImagePath: 'assets/pickaxe.png',
        Description: 'Mine twice as much gold.',
        Modify: 'Mine Gold',
        ModifyType: 'Actions',
        ResourceAdded: [{Name: 'Gold', Amount: 1}],
        ButtonType: 'Upgrade',
        Cost:  {Resources: [{Name: 'Lumber', Amount: 50, Type: 'Resources'}, {Name: 'Gold', Amount: 50, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Owned: 0,
        SpecialUnlock: false, 
        Unlocked: false,
        UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [{Name: 'Miner', Amount: 1, Type: 'Units'}], Upgrades: []},
        Visible: false,
        VisibilityRequirements: {Resources: [], Actions: [], Buildings: [{Name: 'Gold Mine', Amount: 1, Type: 'Buildings'}], Units: [], Upgrades: []},
        FlavorText: '',
        ModalData: {
            Title: '',
            Description: '',
            ButtonTitle: '',
            ModalUpgrades: [],
        },
    },
    {
        Name: 'Establish a guild hall.',
        ImagePath: 'assets/crown.png',
        Description: 'Establish an guild to progress your kingdom!',
        Modify: 'Global',
        ModifyType: 'Global',
        ResourceAdded: [],
        ButtonType: 'Upgrade',
        Cost:  {Resources: [{Name: 'Food', Amount: 250, Type: 'Resources'}, {Name: 'Lumber', Amount: 250, Type: 'Resources'}, {Name: 'Gold', Amount: 250, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
        Owned: 0,
        SpecialUnlock: false, 
        Unlocked: false,
        UnlockRequirements: {Resources: [], Actions: [], Buildings: [{Name: 'Mill', Amount: 3, Type: 'Buildings'}, {Name: 'Lumber Yard', Amount: 3, Type: 'Buildings'}, {Name: 'Gold Mine', Amount: 3, Type: 'Buildings'}], Units: [{Name: 'Peasant', Amount: 3, Type: 'Units'}, {Name: 'Lumberjack', Amount: 3, Type: 'Units'}, {Name: 'Miner', Amount: 3, Type: 'Units'}], Upgrades: []},
        Visible: false,
        VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: [{Name: 'Improved Hoes', Amount: 1, Type: 'Upgrades'}]},
        FlavorText: '',
        ModalData: {
            Title: 'Guild established!',
            Description: 'Your kingdom has begun to grow enough that you feel confident in establishing a guild to grow further. You hold a forum, during which three citizens approach and lobby you to follow their proposed guilds. Which do you choose?',
            ButtonTitle: 'Select',
            ModalUpgrades: [
                {
                    Name: 'Establish a knightly order.',
                    ImagePath: 'assets/coatofarms.jpg',
                    ButtonType: 'Upgrade',
                    Description: 'Using military force, you can send knights to wage war and pillage other kingdoms. They may return with treasure, but beware that you may suffer casualties.',
                    Owned: 0,
                    SpecialUnlock: false,
                    Unlocked: true,
                    UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
                    Visible: true,
                    VisibilityRequirements:  {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
                    FlavorText: '',
                    Selected: false,
                },
                {
                    Name: 'Establish a priesthood.',
                    ImagePath: 'assets/pray.png',
                    ButtonType: 'Upgrade',
                    Description: 'Establish a holy order of priests to accumulate the favor of the gods. Spend favor to unlock powerful, but temporary, blessings from the gods.',
                    Owned: 0,
                    SpecialUnlock: false, 
                    Unlocked: true,
                    UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
                    Visible: true,
                    VisibilityRequirements:  {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
                    FlavorText: '',
                    Selected: false,
                },
                {
                    Name: 'Establish a college of magic.',
                    ImagePath: 'assets/tower.png',
                    ButtonType: 'Upgrade',
                    Description: 'Establish a college of wizards to research arcane knowledge. Use research to unlock spells, which can be cast using mana for immediate benefits.',
                    Owned: 0,
                    SpecialUnlock: false, 
                    Unlocked: true,
                    UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
                    Visible: true,
                    VisibilityRequirements:  {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
                    FlavorText: '',
                    Selected: false,
                },
            ],
        },
    },
];

export const KnightFaction: UserInventory = {
    Fields: [],
    Resources: [],
    Actions: [
        {
            Name: 'Raid Village',
            ImagePath: 'assets/pillagesmall.png',
            Time: 1000,
            TimeLabel: '1m',
            ActionType: 'Raid',
            ButtonType: 'Action',
            Description: 'Send as many knights as possible, up to 5, to raid a nearby village. They will return with pillaged loot, but some may perish.',
            ResourceAdded: [],
            Cost: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Disabled: false,
            Progress: 0,
            Owned: 0,
            SpecialUnlock: false, 
            Unlocked: false,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [{Name: 'Knight', Amount: 1, Type: 'Units'}], Upgrades: []},
            Visible: true,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            FlavorText: 'Greed is good.',
        },
        {
            Name: 'Pillage Castle',
            ImagePath: 'assets/castle.png',
            Time: 5000,
            TimeLabel: '5m',
            ActionType: 'Raid',
            ButtonType: 'Action',
            Description: 'Send as many knights as possible, up to 25, to raid a nearby castle. They will return with pillaged loot, but many will likely perish.',
            ResourceAdded: [],
            Cost: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Disabled: false,
            Progress: 0,
            Owned: 0,
            SpecialUnlock: false, 
            Unlocked: false,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [{Name: 'Knight', Amount: 5, Type: 'Units'}], Upgrades: []},
            Visible: true,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            FlavorText: 'Greed is good.',
        },
    ],
    Buildings: [],
    Units: [
        {
            Name: 'Knight',
            ImagePath: 'assets/knight.jpg',
            ModifiedBuilding: '',
            ResourceAdded: [],
            ButtonType: 'Unit',
            Description: '',
            Cost: {Resources: [{Name: 'Food', Amount: 50, Type: 'Resources'}, {Name: 'Gold', Amount: 50, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Owned: 0,
            SpecialUnlock: false, 
            Unlocked: true,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Visible: true,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            FlavorText: 'We are the Knights who say... NI!',
        },
    ],
    Upgrades: [
        {
            Name: 'Establish a knightly order',
            ImagePath: 'assets/coatofarms.jpg',
            Description: 'Using military force, you can send knights to wage war and pillage other kingdoms. They may return with treasure, but beware that you may suffer casualties.',
            Modify: 'Global',
            ModifyType: 'Global',
            ResourceAdded: [],
            ButtonType: 'Upgrade',
            Cost: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Owned: 1,
            SpecialUnlock: false, 
            Unlocked: true,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [{Name: 'Peasant', Amount: 1, Type: 'Units'}], Upgrades: []},
            Visible: true,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [{Name: 'Mill', Amount: 1, Type: 'Buildings'}], Units: [], Upgrades: []},
            FlavorText: '',
            ModalData: {
                Title: '',
                Description: '',
                ButtonTitle: '',
                ModalUpgrades: [],
            },
        },
        {
            Name: 'Aggressive Tactics',
            ImagePath: 'assets/tactics.png',
            Description: 'A greater understanding of mobilization techniques allows you to continuously send knights on raids.',
            Modify: 'Global',
            ModifyType: 'Global',
            ResourceAdded: [],
            ButtonType: 'Upgrade',
            Cost: {Resources: [{Name: 'Gold', Amount: 500, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Owned: 0,
            SpecialUnlock: false, 
            Unlocked: false,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [{Name: 'Knight', Amount: 25, Type: 'Units'}], Upgrades: []},
            Visible: false,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [{Name: 'Knight', Amount: 1, Type: 'Units'}], Upgrades: []},
            FlavorText: '',
            ModalData: {
                Title: '',
                Description: '',
                ButtonTitle: '',
                ModalUpgrades: [],
            },
        },
    ],
};

export const PriestFaction: UserInventory = {
    Fields: [],
    Resources: [
        {
            Name: 'Favor',
            Owned: 0,
            SpecialUnlock: false,
            Unlocked: true,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Visible: true,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
        },
    ],
    Actions: [
        {
            Name: 'Collect tithes',
            ImagePath: 'assets/tithe.png',
            Time: 1000,
            TimeLabel: '1m',
            ActionType: 'Harvest',
            ButtonType: 'Action',
            Description: 'Pay tithes to the church, sacrificing gold for favor.',
            Cost: {Resources: [{Name: 'Gold', Amount: 100, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
            ResourceAdded: [{Name: 'Favor', Amount: 10}],
            Disabled: false,
            Progress: 0,
            Owned: 0,
            SpecialUnlock: false, 
            Unlocked: false,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [{Name: 'Priest', Amount: 1, Type: 'Units'}], Upgrades: []},
            Visible: true,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            FlavorText: 'En comish cumprampre',
        },
    ],
    Buildings: [
        {
            Name: 'Church',
            ImagePath: 'assets/church.png',
            Time: 10000,
            TimeLabel: '10s',
            ButtonType: 'Building',
            Description: '',
            ResourceAdded: [{Name: 'Favor', Amount: 10}],
            Cost: {Resources: [{Name: 'Lumber', Amount: 100, Type: 'Resources'}, {Name: 'Gold', Amount: 150, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Owned: 0,
            Progress: 0,
            SpecialUnlock: false, 
            Unlocked: true,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Visible: true,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            FlavorText: '',
        },
    ],
    Units: [
        {
            Name: 'Priest',
            ImagePath: 'assets/priest.png',
            ModifiedBuilding: 'Church',
            ButtonType: 'Unit',
            Description: '',
            ResourceAdded: [{Name: 'Favor', Amount: 5}],
            Cost: {Resources: [{Name: 'Food', Amount: 15, Type: 'Resources'}, {Name: 'Gold', Amount: 50, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Owned: 0,
            SpecialUnlock: false, 
            Unlocked: true,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Visible: true,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            FlavorText: 'En cumpra mfinde.',
        },
    ],
    Upgrades: [
        {
            Name: 'Establish a priesthood.',
            ImagePath: 'assets/pray.png',
            Description: 'Establish a holy order of priests to accumulate the favor of the gods. Spend favor to unlock powerful, but temporary, blessings from the gods. ',
            Modify: 'Global',
            ModifyType: 'Global',
            ButtonType: 'Upgrade',
            ResourceAdded: [],
            Cost: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Owned: 1,
            SpecialUnlock: false, 
            Unlocked: true,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Visible: true,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            FlavorText: '',
            ModalData: {
                Title: '',
                Description: '',
                ButtonTitle: '',
                ModalUpgrades: [],
            },
        },
    ],
};

export const WizardFaction: UserInventory = {
    Fields: [],
    Resources: [
        {
            Name: 'Mana',
            Owned: 10000,
            SpecialUnlock: false,
            Unlocked: true,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Visible: true,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
        },
    ],
    Actions: [
        {
            Name: 'Harvest Manastone',
            ImagePath: 'assets/manastone.png',
            Time: 1000,
            TimeLabel: '1m',
            ActionType: 'Harvest',
            ButtonType: 'Action',
            Description: '',
            Cost: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            ResourceAdded: [{Name: 'Mana', Amount: 10}],
            Disabled: false,
            Progress: 0,
            Owned: 0,
            SpecialUnlock: false, 
            Unlocked: true,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Visible: true,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            FlavorText: '',
        },
        {
            Name: 'Experiment',
            ImagePath: 'assets/experiment.png',
            Time: 1000,
            TimeLabel: '1m',
            ActionType: 'Spell',
            ButtonType: 'Action',
            Description: 'Cast an experimental spell. May teach your wizards how to cast new spells, or it may backfire.',
            ResourceAdded: [],
            Cost: {Resources: [{Name: 'Mana', Amount: 100, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Disabled: false,
            Progress: 0,
            Owned: 0,
            SpecialUnlock: false, 
            Unlocked: false,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [{Name: 'Wizard', Amount: 1, Type: 'Units'}], Upgrades: []},
            Visible: true,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            FlavorText: 'I meant to do that.',
        },
        {
            Name: 'Midas Touch',
            ImagePath: 'assets/experiment.png',
            Time: 1000,
            TimeLabel: '1m',
            ActionType: 'Spell',
            ButtonType: 'Action',
            Description: 'Transmute a random amount of lumber into a random amount of gold. Transmutes more food if you have more wizards. Slight chance to backfire.',
            ResourceAdded: [],
            Cost: {Resources: [{Name: 'Mana', Amount: 50, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Disabled: false,
            Progress: 0,
            Owned: 0,
            SpecialUnlock: true, 
            Unlocked: false,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Visible: false,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            FlavorText: 'Hopefully this works out better for you than it did for Midas.',
        },
        {
            Name: 'Conjure Golem',
            ImagePath: 'assets/experiment.png',
            Time: 2000,
            TimeLabel: '5m',
            ActionType: 'Spell',
            ButtonType: 'Action',
            Description: 'Use the gold you have laying around to conjure a golem that helps increase all production.',
            ResourceAdded: [],
            Cost: {Resources: [{Name: 'Mana', Amount: 500, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Disabled: false,
            Progress: 0,
            Owned: 0,
            SpecialUnlock: true, 
            Unlocked: false,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Visible: false,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            FlavorText: '',
        }
    ],
    Buildings: [
        {
            Name: 'Library',
            ImagePath: 'assets/church.png',
            Time: 10000,
            TimeLabel: '10s',
            ButtonType: 'Building',
            Description: '',
            ResourceAdded: [{Name: 'Mana', Amount: 1}],
            Cost: {Resources: [{Name: 'Lumber', Amount: 250, Type: 'Resources'}, {Name: 'Gold', Amount: 250, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Owned: 0,
            Progress: 0,
            SpecialUnlock: false, 
            Unlocked: true,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Visible: true,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            FlavorText: '',
        },
    ],
    Units: [
        {
            Name: 'Wizard',
            ImagePath: 'assets/wizard.png',
            ModifiedBuilding: 'Library',
            ButtonType: 'Unit',
            Description: '',
            ResourceAdded: [{Name: 'Mana', Amount: 5}],
            Cost: {Resources: [{Name: 'Food', Amount: 15, Type: 'Resources'}, {Name: 'Mana', Amount: 50, Type: 'Resources'}], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Owned: 0,
            SpecialUnlock: false, 
            Unlocked: true,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Visible: true,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            FlavorText: '',
        },
        {
            Name: 'Golem',
            ImagePath: 'assets/wizard.png',
            ModifiedBuilding: 'Library',
            ButtonType: 'Unit',
            Description: 'Each golem adds 1 to the production of each building. Cannot be recruited through traditional means, only conjured.',
            ResourceAdded: [],
            Cost: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Owned: 0,
            SpecialUnlock: true, 
            Unlocked: false,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Visible: false,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            FlavorText: '',
        },
    ],
    Upgrades: [
        {
            Name: 'Establish a college of magic.',
            ImagePath: 'assets/tower.png',
            Description: 'Establish a college of wizards to research arcane knowledge. Use research to unlock spells, which can be cast using mana for immediate benefits.',
            Modify: 'Global',
            ModifyType: 'Global',
            ButtonType: 'Upgrade',
            ResourceAdded: [],
            Cost: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Owned: 1,
            SpecialUnlock: false, 
            Unlocked: true,
            UnlockRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            Visible: true,
            VisibilityRequirements: {Resources: [], Actions: [], Buildings: [], Units: [], Upgrades: []},
            FlavorText: '',
            ModalData: {
                Title: '',
                Description: '',
                ButtonTitle: '',
                ModalUpgrades: [],
            },
        },
    ],
};

